name: Build APK (Debug, old AGP via mirrors)

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) sdkmanager 需要 JDK17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" \
                     "platforms;android-25" "platforms;android-23" "platforms;android-28" \
                     "build-tools;25.0.3" "build-tools;23.0.3" "build-tools;28.0.3"

      # 2) 全局注入仓库镜像（含阿里云 mirrors）
      - name: Inject global repositories & mirrors
        run: |
          mkdir -p ~/.gradle/init.d
          cat > ~/.gradle/init.d/repo.gradle <<'EOF'
          allprojects { proj ->
            def repos = {
              maven { url "https://dl.google.com/dl/android/maven2/" }
              maven { url "https://maven.google.com" }
              mavenCentral()
              jcenter()
              // Mirrors（帮助拉到历史工件）
              maven { url "https://maven.aliyun.com/repository/google" }
              maven { url "https://maven.aliyun.com/repository/central" }
              maven { url "https://maven.aliyun.com/repository/jcenter" }
              maven { url "https://maven-central.storage-download.googleapis.com/maven2" }
            }
            buildscript { repositories repos }
            repositories repos
          }
          EOF

      # 3) 把 2.3.2 提升到 2.3.3（更容易拉到）
      - name: Bump AGP from 2.3.2 to 2.3.3
        run: |
          grep -RIl "com.android.tools.build:gradle:2.3.2" || true
          sed -i 's/com.android.tools.build:gradle:2\.3\.2/com.android.tools.build:gradle:2.3.3/g' build.gradle || true
          sed -i 's/com.android.tools.build:gradle:2\.3\.2/com.android.tools.build:gradle:2.3.3/g' */build.gradle || true

      # 4) 切回 JDK8 构建（Gradle 3.3 需要）
      - name: Switch to JDK 8 for build
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: List built APKs
        run: |
          echo "Searching for APKs under */build/outputs/apk ..."
          find . -path "*/build/outputs/apk/*/*.apk" -print || true

      - name: Build debug APK (fallback try all)
        run: |
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact (any module)
        uses: actions/upload-artifact@v4
        with:
          name: MiNotes-debug-apk
          path: |
            **/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/*/debug/*.apk
            **/build/outputs/apk/*.apk
