name: Build APK (Debug, Simple)

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 先用 JDK 11（旧项目更兼容；若还不行再换 17）
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 一键装好 ANDROID_SDK_ROOT、sdkmanager 等
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 安装常见的 platforms / build-tools（覆盖多数老项目）
      - name: Install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" \
                     "platforms;android-34" "platforms;android-33" "platforms;android-30" \
                     "build-tools;34.0.0" "build-tools;33.0.2" "build-tools;30.0.3"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build debug APK
        run: |
          ./gradlew --no-daemon clean
          ./gradlew --no-daemon --stacktrace --info assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiNotes-debug-apk
          path: '**/build/outputs/apk/debug/*.apk'
